name: Ola Mundo

on:
  push:
  workflow_dispatch:

jobs:
  minha-tarefa:
    runs-on: ubuntu-latest
    steps:
      - name: Dizer ola
        run: echo "Olá, mundo! Meu primeiro GitHub Action."

      - name: Trocar a Mensagem
        run: echo "Fernanda da Costa Aguiar"

      - name: Mostrar data e hora
        run: date

      - name: Descobrir quem fez o commit
        run: echo "Commit feito por ${{ github.actor }}"
